steps: 
  - id: "run bashh"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          ls
     
  - id: 'build your instance'
    name: 'maven:3.6.0-jdk-11-slim'
    entrypoint: mvn
    args: ['clean','package','-Dmaven.test.skip=true']
    dir: "run/helloworld"
  - id: "run bash"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args: ['gsutil','cp','gs://sarthakbucket/test.json.enc','.']
  - id: "run bashhhhh"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args: ['gcloud','kms','decrypt','--plaintext-file=test.json','--ciphertext-file=test.json.enc','--location=global','--keyring=test','--key=mykey']  
  - id: "run bashhh"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          cp ./test.json ./run
  - id: "run bashhhhhh"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          cd run
          ls
  - id: 'Deploy image to kubernetes'
    name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=./run/helloworld/src
    - --location=us-central1-c
    - --cluster=cluster-2
    env:
    - 'ENV=${_ENV}'
     
