steps: 
  - id: "run bashh"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          ls
     
  - id: 'build your instance'
    name: 'maven:3.6.0-jdk-11-slim'
    entrypoint: mvn
    args: ['clean','package','-Dmaven.test.skip=true']
    dir: "run/helloworld"
  - id: "run bash"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args: ['gsutil','cp','gs://sarthakbucket/test.json.enc']     
  - id: "run bashhh"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          ls        
 # - id: 'Deploy image to kubernetes'
  #  name: 'gcr.io/cloud-builders/gke-deploy'
   # args:
    #- run
   # - --filename=./run/helloworld/src
   # - --location=us-central1-c
   # - --cluster=cluster-1    
     
