steps: 
  - id: "run bash"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          ls
    dir: "run/helloworld" 
  - id: 'build your instance'
    name: 'maven:3.6.0-jdk-11-slim'
    entrypoint: mvn
    args: ['clean','package']
    dir: "run/helloworld"
  - id: 'build your instancee'
    name: 'maven:3.6.0-jdk-11-slim'
    entrypoint: mvn
    args: ['compile','jib:build']
    dir: "run/helloworld"
  - id: 'Deploy image to kubernetes'
    name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=./src
    - --image=gcr.io/$PROJECT_ID/jib:latest
    - --location=us-central1-c
    - --cluster=cluster-1 
     
