  steps: 
  - id: "run bashh"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          ls
          cat "this is new pipeline"
  - id: 'build your instance'
    name: 'maven:3.6.0-jdk-11-slim'
    entrypoint: mvn
    args: ['clean','package']
    dir: "run/helloworld"
  
  - id: 'buildd your instance'
    name: 'maven:3.6.0-jdk-11-slim'
    entrypoint: mvn
    args: ['deploy']
    dir: "run/helloworld"  
  
#    env:
 #    - 'VALUE=${_VALUE}'
 # - id: Deploy
 #   name: 'gcr.io/cloud-builders/kubectl'  
 #   args:
 #   - 'apply'
 #   - '-f'
 #   - 'run/helloworld/src/deployment.yaml'
 #   env:
#    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
 #   - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
 # - id: "run bashhhhhhhh"
#    name: 'gcr.io/cloud-builders/gcloud'
#    entrypoint: "bash"
#    args:
#      - "-c"
#      - |
#          cat  run/helloworld/src/deployment1.yaml    
  
#  - id: 'Deploy image to kubernetes'
#    name: 'gcr.io/cloud-builders/gke-deploy'
#    args:
#    - run
 #   - --filename=./run/helloworld/src
#    - --location=us-central1-c
 #   - --cluster=cluster-1
  
 # timeout: 1200s    
   
     
