  steps: 
  - id: "run bashh"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          ls
     
  - id: 'build your instance'
    name: 'maven:3.6.0-jdk-11-slim'
    entrypoint: mvn
    args: ['clean','package','-Dmaven.test.skip=true']
    dir: "run/helloworld"
  - id: 'Building image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mytest','--cache-from', 'gcr.io/$PROJECT_ID/mytest:latest' '.']
  
    dir: "run/helloworld"
  
  #- id: 'building docker image'
  #  name: 'gcr.io/cloud-builders/docker'
  #  args: ['build','-t', 'gcr.io/${PROJECT_ID}/mytest','.']
  #  dir: "run/helloworld"
#  - id: 'Pushing docker image'
#    name: 'gcr.io/cloud-builders/docker'
#    args: ['push', 'gcr.io/$PROJECT_ID/mytest']
#    dir: "run/helloworld"
 # - name: 'gcr.io/cloud-builders/docker'
 #   entrypoint: 'bash'
 #   args: ['-c', 'docker pull gcr.io/$PROJECT_ID/mytest:latest || exit 0']
# -  name: 'gcr.io/cloud-builders/docker'
 #   args: [
 #           'build',
 #           '-t', 'gcr.io/$PROJECT_ID/mytest:latest',
  #          '--cache-from', 'gcr.io/$PROJECT_ID/mytest:latest',
  #          '.'
          ]
  # images: ['gcr.io/$PROJECT_ID/mytest:latest']
   # dir: "run"
  
 # - id: "run bashhhhhh"
 #   name: 'gcr.io/cloud-builders/gcloud'
 #   entrypoint: "bash"
 #   args:
  #    - "-c"
   #   - |
   #       cd run
   #       ls
  
  - id: Generate manifest
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
     sed -i -e  "s/mvalue/${_VALUE}/g"  -e "s/hello/world/g"  -e "s/tomcat-imagesss/image/g"  run/helloworld/src/deployment1.yaml
     cat  run/helloworld/src/deployment1.yaml
#    env:
 #    - 'VALUE=${_VALUE}'
  - id: Deploy
    name: 'gcr.io/cloud-builders/kubectl'  
    args:
    - 'apply'
    - '-f'
    - 'run/helloworld/src/deployment.yaml'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
  - id: "run bashhhhhhhh"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          cat  run/helloworld/src/deployment1.yaml    
  
  - id: 'Deploy image to kubernetes'
    name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=./run/helloworld/src
    - --location=us-central1-c
    - --cluster=cluster-1
  images: 'gcr.io/$PROJECT_ID/mytest:latest'
  timeout: 1200s    
   
     
