  steps: 
  - id: "run bashh"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          ls
  - id: 'Deploy image to kubernetes'
    name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=./run/helloworld/src/deployment.yaml
    - --location=us-central1-c
    - --cluster=cluster-1
