  steps: 
  - id: "run bashh"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      sed -i -e "s/private-reg-containers/{_TEST}" run/helloworld/src/deployment.yaml
  
  - id: "run bashh"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
       cat run/helloworld/src/deployment.yaml    
  
  - id: delete
    name: 'gcr.io/cloud-builders/kubectl'  
    args:
    - 'delete'
    - 'pod'
    - '$_DEP'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'  
  - id: 'Deploy image to kubernetes'
    name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=./run/helloworld/src/deployment.yaml
    - --location=us-central1-c
    - --cluster=cluster-1
