  steps: 
  - id: "run bashh"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
    - '-c'
    - |
      sed  's/private-reg-containers/{_TEST}' run/helloworld/src/deployment.yaml
  
  - id: "run bashhh"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
    - '-c'
    - |
      cat run/helloworld/src/deployment.yaml    
    
  - id: 'Deploy image to kubernetes'
    name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=./run/helloworld/src/deployment.yaml
    - --location=us-central1-c
    - --cluster=cluster-1
  - id: Generate manifest
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
     gcloud builds submit --config cloudbuild.yaml .
    dir: "run/helloworld" 
