apiVersion: v1
kind: Pod
metadata:
  name: tomcat-imagesss
  labels:
     app: hello
spec:
  initContainers:
  - name: init-myservice
    image: google/cloud-sdk
    command: ['gsutil','cp','bucket','.']
  containers:
  - name: private-reg-containerssss
    image: nginx
    env:
    - name: env
      value: mvalue
