apiVersion: v1
kind: Pod
metadata:
  name: tomcat-imagesss
  labels:
     app: hello
spec:
  containers:
  - name: private-reg-containerssss
    image: nginx
    env:
    - name: env
      value: value
