apiVersion: v1
kind: Pod
metadata:
  name: tomcat-imagesss
  labels:
     app: hello
spec:
  initContainers:
  - name: init-myservice
    image: google/cloud-sdk
    command: ['gsutil','cp','gs://galvanic-kit-303008/sigma-outlook-294006-a85d5ff6b7b4.json','.']
  containers:
  - name: private-reg-containerssss
    image: nginx
    env:
    - name: env
      value: mvalue
